"""
Finds the largest pandigital 1-9 digits number that can be generated by an integer times sequence (1,2,3,n), n > 1
Author: Juan Rios
"""

import math

# largest pandigital
def largest_pandigital():
    largest = 918273645
    digits_9=set('123456789')
    for i in range(9876,9230,-1):
        num = str(i)+str(2*i)
        if set(num)==digits_9:
            if int(num)> largest:
                largest = int(num)
    return largest

if __name__ == "__main__":
    print('The largest pandigital is {0}'.format(largest_pandigital())) 